spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jackson:
    serialization: true

server:
  tomcat:
    uri-encoding: UTF-8


